#!/usr/bin/env bash
function apply() {
    local stack="${1}"
    [[ ! -d "${stack}/.terraform" ]] && terraform -chdir="${stack}" init
    terraform -chdir="${stack}" apply "${@:2}"
}

set -e
cd "$(dirname "$0")" || exit 1
apply "nodes" "${@}"
if ! terraform -chdir="cluster" state list "module.metallb.helm_release.metallb_release"; then
    apply "cluster" "${@}" \
        -target="module.metallb.helm_release.metallb_release" \
        -target="module.envoy.helm_release.envoy_gateway_release"
fi
apply "cluster" "${@}"
